### ISSUE TITLE
Loading to slow to a halt at the end, unplayable 2fps frame rate

### ISSUE THREAD

**Issue by Kovoschiz** [klyte45/WriteEverywhere#2]
As titled. Loading stuck at main thread `Update Render Group` simulation thread `RenderManager.LateUpdateData` for 3 minutes. When loaded, it is 2fps ~500ms frame rate. When I finally decide to unsubscribe from this, it worked. 
Sorry I don't want to reproduce it now, as I spent at least half an hour trying figuring out what's wrong. I checked there appears no errors appearing anyway. So here's my current setup: https://kovoschiz.github.io/CompatibilityReport.html (not sure how to share the HTML files, but this should work?) 
I don't think you want to look at a working `output_log.txt` ? Here's the system part only: 
```
Initialize engine version: 5.6.7f1 (e80cc3114ac1)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: AMD Radeon RX 6700 XT (ID=0x73df)
    Vendor:   ATI
    VRAM:     12243 MB
    Driver:   31.0.12002.92
```
I will try to reproduce it when I play next if this is an unknown issue you want to look into.

**Comment by klyte45** [comment]
I will close this and ask you to reopen this issue using the bug template that I just added. There are all information I need to check.
