### ISSUE TITLE
Game stats variable empty[BUG]

### ISSUE THREAD

**Issue by MonsMarm** [klyte45/WriteEverywhere#3]
**Describe the bug**
When trying to set parametrized signs, I see no variables listed under "Game stats variable" menu. I have CD UU VS mods (all latest).

**To Reproduce**
1. open the mod
2. pick the vehicle or road with the picker
3. create new sign
4. set the content to game stat variable

**Game Logs**
[2022-11-14 18:10:19.3078][WE  ][v0.1.0 r5    ][WARNING ] Patching all: com.klyte.redirectors.WE

**Screenshots**
I'm getting this in mods tool prompt:
![image](https://user-images.githubusercontent.com/118205552/201725892-31916034-35f3-4a9f-a845-2a577b15bba4.png)
and this is what appears in the WE window:
![image](https://user-images.githubusercontent.com/118205552/201726044-455def02-d6b1-4d9c-bbda-1a39a89e324d.png)

**Additional context**
The same happens for vehicles (metro) and roads. I did not try other things.

**Comment by WolverineCTX** [comment]
Got the same issue (as Klyte45 already knows about on our Discord conversation) - just here to second that Bug Report.
![Screenshot_92](https://user-images.githubusercontent.com/114856109/201978039-85970b8e-d4a4-4afa-a893-2c3cb776cce4.png)

**Comment by klyte45** [comment]
It was fixed in v0.1.0r8
